// web/src/components/AddTask.vue
<template>
  <div class="add-task-form">
    <h3>Add New Task</h3>
    <form @submit.prevent="addTask">
      <div class="form-group">
        <label for="eventId">Event ID:</label>
        <input id="eventId" v-model.number="newTask.eventId" type="number" required placeholder="Enter event ID" />
      </div>

      <div class="form-group">
        <label for="description">Description:</label>
        <textarea id="description" v-model="newTask.description" required placeholder="Enter task description"></textarea>
      </div>

      <div class="form-group">
        <label for="status">Status:</label>
        <select id="status" v-model="newTask.status" required>
          <option value="">Select status</option>
          <option value="pending">Pending</option>
          <option value="in_progress">In Progress</option>
          <option value="completed">Completed</option>
          <option value="cancelled">Cancelled</option>
        </select>
      </div>

      <div class="form-group">
        <label for="allowedStart">Allowed Start (optional):</label>
        <input id="allowedStart" v-model="newTask.allowedStart" type="datetime-local" />
      </div>

      <div class="form-group">
        <label for="allowedEnd">Allowed End (optional):</label>
        <input id="allowedEnd" v-model="newTask.allowedEnd" type="datetime-local" />
      </div>

      <div class="form-group">
        <label for="plannedStart">Planned Start (optional):</label>
        <input id="plannedStart" v-model="newTask.plannedStart" type="datetime-local" />
      </div>

      <div class="form-group">
        <label for="plannedEnd">Planned End (optional):</label>
        <input id="plannedEnd" v-model="newTask.plannedEnd" type="datetime-local" />
      </div>

      <button type="submit" :disabled="adding">Add Task</button>
      <div v-if="error" class="error">{{ error }}</div>
      <div v-if="success" class="success">Task added successfully!</div>
    </form>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { createTask } from '../api/task'
import type { TaskCreateRequest } from '../api/types'

const emit = defineEmits<{
  (e: 'task-added'): void
}>()

const newTask = ref({
  eventId: null as number | null,
  description: '',
  status: '',
  allowedStart: '',
  allowedEnd: '',
  plannedStart: '',
  plannedEnd: ''
})

const adding = ref(false)
const error = ref('')
const success = ref(false)

const addTask = async () => {
  if (!newTask.value.eventId || !newTask.value.description || !newTask.value.status) {
    error.value = 'Event ID, Description, and Status are required'
    return
  }

  try {
    adding.value = true
    error.value = ''
    success.value = false

    const taskData: TaskCreateRequest = {
      eventId: newTask.value.eventId,
      description: newTask.value.description,
      status: newTask.value.status,
      allowedStart: newTask.value.allowedStart || undefined,
      allowedEnd: newTask.value.allowedEnd || undefined,
      plannedStart: newTask.value.plannedStart || undefined,
      plannedEnd: newTask.value.plannedEnd || undefined
    }

    await createTask(taskData)
    success.value = true
    emit('task-added')

    // Reset form
    newTask.value = {
      eventId: null,
      description: '',
      status: '',
      allowedStart: '',
      allowedEnd: '',
      plannedStart: '',
      plannedEnd: ''
    }
  } catch (err) {
    error.value = 'Failed to add task'
    console.error('Error adding task:', err)
  } finally {
    adding.value = false
  }
}
</script>

<style scoped>
.add-task-form {
  background: #f8f9fa;
  padding: 20px;
  border-radius: 8px;
  margin-bottom: 30px;
}

.add-task-form h3 {
  margin-top: 0;
  color: #2c3e50;
}

.form-group {
  margin-bottom: 15px;
}

.form-group label {
  display: block;
  margin-bottom: 5px;
  font-weight: 500;
}

.form-group input,
.form-group select,
.form-group textarea {
  width: 100%;
  padding: 8px 12px;
  border: 1px solid #ddd;
  border-radius: 4px;
  font-size: 14px;
}

.form-group textarea {
  min-height: 80px;
  resize: vertical;
}

button {
  padding: 10px 20px;
  background: #3498db;
  color: white;
  border: none;
  border-radius: 4px;
  cursor: pointer;
  font-size: 14px;
}

button:hover {
  background: #2980b9;
}

button:disabled {
  background: #bdc3c7;
  cursor: not-allowed;
}

.error {
  color: #e74c3c;
  margin-top: 10px;
}

.success {
  color: #27ae60;
  margin-top: 10px;
}
</style>

// web/src/components/AddTask.tsx
import { createSignal } from 'solid-js'
import { createTask } from '../api/task'
import type { TaskCreateRequest } from '../api/types'
import styles from './AddTask.module.css'

interface Props {
  onTaskAdded: () => void
}

/**
 * AddTask组件 - 负责添加新任务
 * 
 * SolidJS概念解释:
 * - 使用createSignal管理本地表单状态
 * - 通过props接收回调函数，在任务添加成功后通知父组件
 * - 表单提交使用事件处理函数
 */
export default function AddTask(props: Props) {
  const [formData, setFormData] = createSignal({
    eventId: '',
    parentTaskId: '',
    description: '',
    allowedStart: '',
    allowedEnd: '',
    plannedStart: '',
    plannedEnd: '',
    status: 'pending'
  })

  const [loading, setLoading] = createSignal(false)
  const [error, setError] = createSignal('')

  // 更新表单字段的辅助函数
  type FormFields = 'eventId' | 'parentTaskId' | 'description' | 'allowedStart' | 'allowedEnd' | 'plannedStart' | 'plannedEnd' | 'status'
  const updateFormField = (field: FormFields, value: string) => {
    setFormData(prev => ({ ...prev, [field]: value }))
  }

  // 处理表单提交
  const handleSubmit = async (e: Event) => {
    e.preventDefault()
    
    const currentFormData = formData()
    if (!currentFormData.eventId || !currentFormData.description) {
      setError('Event ID and Description are required')
      return
    }

    try {
      setLoading(true)
      setError('')

      const taskData: TaskCreateRequest = {
        eventId: parseInt(currentFormData.eventId),
        parentTaskId: currentFormData.parentTaskId ? parseInt(currentFormData.parentTaskId) : undefined,
        preTaskIds: [], // 暂时为空，可以根据需要扩展
        description: currentFormData.description,
        allowedStart: currentFormData.allowedStart || undefined,
        allowedEnd: currentFormData.allowedEnd || undefined,
        plannedStart: currentFormData.plannedStart || undefined,
        plannedEnd: currentFormData.plannedEnd || undefined,
        status: currentFormData.status
      }

      await createTask(taskData)
      
      // 重置表单
      setFormData({
        eventId: '',
        parentTaskId: '',
        description: '',
        allowedStart: '',
        allowedEnd: '',
        plannedStart: '',
        plannedEnd: '',
        status: 'pending'
      })

      // 通知父组件任务已添加
      props.onTaskAdded()
      
    } catch (err) {
      setError('Failed to add task')
      console.error('Error adding task:', err)
    } finally {
      setLoading(false)
    }
  }

  return (
    <div class={styles.addTaskForm}>
      <h3>Add New Task</h3>
      <form onSubmit={handleSubmit}>
        <div class={styles.formGroup}>
          <label for="eventId">Event ID:</label>
          <input
            id="eventId"
            type="number"
            value={formData().eventId}
            onInput={(e) => updateFormField('eventId', e.currentTarget.value)}
            required
            placeholder="Enter event ID"
          />
        </div>

        <div class={styles.formGroup}>
          <label for="parentTaskId">Parent Task ID (optional):</label>
          <input
            id="parentTaskId"
            type="number"
            value={formData().parentTaskId}
            onInput={(e) => updateFormField('parentTaskId', e.currentTarget.value)}
            placeholder="Enter parent task ID"
          />
        </div>

        <div class={styles.formGroup}>
          <label for="description">Description:</label>
          <textarea
            id="description"
            value={formData().description}
            onInput={(e) => updateFormField('description', e.currentTarget.value)}
            required
            placeholder="Enter task description"
            rows={3}
          />
        </div>

        <div class={styles.formGroup}>
          <label for="status">Status:</label>
          <select
            id="status"
            value={formData().status}
            onChange={(e) => updateFormField('status', e.target.value)}
          >
            <option value="pending">Pending</option>
            <option value="in_progress">In Progress</option>
            <option value="completed">Completed</option>
            <option value="cancelled">Cancelled</option>
          </select>
        </div>

        <div class={styles.formRow}>
          <div class={styles.formGroup}>
            <label for="allowedStart">Allowed Start (optional):</label>
            <input
              id="allowedStart"
              type="datetime-local"
              value={formData().allowedStart}
              onChange={(e) => updateFormField('allowedStart', e.target.value)}
            />
          </div>

          <div class={styles.formGroup}>
            <label for="allowedEnd">Allowed End (optional):</label>
            <input
              id="allowedEnd"
              type="datetime-local"
              value={formData().allowedEnd}
              onChange={(e) => updateFormField('allowedEnd', e.target.value)}
            />
          </div>
        </div>

        <div class={styles.formRow}>
          <div class={styles.formGroup}>
            <label for="plannedStart">Planned Start (optional):</label>
            <input
              id="plannedStart"
              type="datetime-local"
              value={formData().plannedStart}
              onChange={(e) => updateFormField('plannedStart', e.target.value)}
            />
          </div>

          <div class={styles.formGroup}>
            <label for="plannedEnd">Planned End (optional):</label>
            <input
              id="plannedEnd"
              type="datetime-local"
              value={formData().plannedEnd}
              onChange={(e) => updateFormField('plannedEnd', e.target.value)}
            />
          </div>
        </div>

        {error() && <div class={styles.errorMessage}>{error()}</div>}

        <button type="submit" disabled={loading()} class={styles.button}>
          {loading() ? 'Adding...' : 'Add Task'}
        </button>
      </form>
    </div>
  )
}
